#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:15
#    container_name: postgres_db
#    restart: always
#    ports:
#      - "5432:5432" # Maps the container's PostgreSQL port to your local machine
#    environment:
#      POSTGRES_USER: vigan
#      POSTGRES_PASSWORD: vigan
#      POSTGRES_DB: music
#    volumes:
#      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data
#
#volumes:
#  postgres_data:
#
#services:
#  wp-db:
#    # Create a service named db.
#    image: postgres:15
#    container_name: postgres_db
#    # Setup the username, password, and database name. You can change these values.
#    environment:
#      - POSTGRES_USER=vigan
#      - POSTGRES_PASSWORD=vigan
#      - POSTGRES_DB=music
#    # Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fit your needs.
#    ports:
#      - "5431:5431"
#    # Set a volume so that the database is not lost after shutting down the container.
#    # I used the name postgres-data but you can change it to something else.
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
